#   __  __      _ _               ______ _
#  |  \/  |    | | |             |  ____(_)
#  | \  / | ___| | | _____      _| |__   _ _ __ ___
#  | |\/| |/ _ \ | |/ _ \ \ /\ / /  __| | | '__/ _ \
#  | |  | |  __/ | | (_) \ V  V /| |    | | | |  __/
#  |_|  |_|\___|_|_|\___/ \_/\_/ |_|    |_|_|  \___|
#  https://www.mellowfire.com/


##names to change if duplicating##
  #up_pin_0
  #down_pin_0
  #top_endstop_0
  #bottom_endstop_0
  #my_cover_0
  #My Endstop Cover 0
  #interlock_group_0

switch:
  - platform: gpio
    pin: #change PIN
    id: up_pin_0
    interlock: &interlock_group_0 [up_pin_0, down_pin_0]
    restore_mode: always off

  - platform: gpio
    pin: #change PIN
    id: down_pin_0
    interlock: *interlock_group_0
    restore_mode: always off


binary_sensor:
  - platform: gpio
    pin: #change PIN
    id: top_endstop_0
  - platform: gpio
    pin: #change PIN
    id: bottom_endstop_0

cover:
  - platform: endstop
    name: "My Endstop Cover 0"
    id: my_cover_0
    open_action:
      - switch.turn_on: up_pin_0
    open_duration: #change time
    open_endstop: top_endstop_0

    close_action:
      - switch.turn_on: down_pin_0
    close_duration: #change time
    close_endstop: bottom_endstop_0
    stop_action:
      - switch.turn_off: up_pin_0
      - switch.turn_off: down_pin_0
    max_duration: #change time